language: java
jdk:
- openjdk8
addons:
  ssh_known_hosts: 185.22.152.167

before_install:


#
#- eval "$(ssh-agent -s)"
#- chmod 600 ./deploy_key
#- echo -e "Host $SERVER_IP_ADDRESS\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
#- ssh-add ./deploy_key
