language: java
jdk:
- openjdk8
addons:
  ssh_known_hosts: 185.22.152.167
before_install:
- openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv
  -in deploy_rsa.enc -out $TRAVIS_BUILD_DIR/deploy_rsa -d
after_success:
  - eval "$(ssh-agent -s)"
  - chmod 600 $TRAVIS_BUILD_DIR/deploy_rsa
  - ssh-add $TRAVIS_BUILD_DIR/deploy_rsa
  - rsync -az --delete-after $TRAVIS_BUILD_DIR/ root@185.22.152.167:../opt/app/